### ISSUE TITLE
Use With VirtualMail

### ISSUE THREAD

**Issue by olynch** [derek-zhou/liv#1]
How would you suggest modifying this for use with virtualmail delivered to /var/vmail/<domain>/<user>? I'm willing to get my hands dirty, but a couple pointers would be helpful.

**Comment by derek-zhou** [comment]
Right now I have no idea. The whole security model of LIV is based on one server process per user, using traditional UNIX user privilege separation. A virtual users and multi-user deployment will let loose a whole can of worm for security concerns.

It will be a scope of a SaaS startup, not a solo project anymore.

**Comment by derek-zhou** [comment]
virtual mail is outside the scope of this project. Closing

**Comment by olynch** [comment]
OK, then I guess I have to figure out how to make my server deliver to UNIX users!

**Comment by derek-zhou** [comment]
IMHO, virtual mail only make sense for large scale deployment. A few years ago, I ran email (SMTP/IMAP/Sogo) for an organization of 100+ active users. Delivering to Unix users work fine. I did have LDAP and kerberos though. For the intended usage case of LIV, which should have very few users, I wouldn't bother with LDAP or kerberos. Flat file /etc/passwd is good enough.
