### ISSUE TITLE
Authenticity is not established by certificate path validation

### ISSUE THREAD

**Issue by olynch** [derek-zhou/liv#2]
It seems like when I try to send an email with liv, it gives me a warning, and I'm not sure what the warning means:

```
Sep 27 10:46:48 proqqul liv[1568395]:   Transport: :websocket
Sep 27 10:46:48 proqqul liv[1568395]:   Serializer: Phoenix.Socket.V2.JSONSerializer
Sep 27 10:46:48 proqqul liv[1568395]:   Parameters: %{"vsn" => "2.0.0"}
Sep 27 10:48:08 proqqul liv[1568395]: 10:48:08.426 [warn] Description: 'Authenticity is not established by certificate path validation'
Sep 27 10:48:08 proqqul liv[1568395]:      Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
```

Also, I was very surprised that liv managed to send an email at all, given that I hadn't given it my mail password. Do SMTP servers typically just accept requests from localhost?

**Comment by derek-zhou** [comment]
Yes. local un-auth SMTP is a very common practice. It is the same as sendmail security wise, but more adherence to the correct mail format.

**Comment by derek-zhou** [comment]
I don't think this warning is from SMTP per se, because local SMTP will not do STARTTLS handshake anyway. Are you running phoenix with SSL? I'd recommend not to do SSL in erlang/elixir, but use a reverse proxy such as nginx. However, you are free to do whatever you want.

**Comment by derek-zhou** [comment]
No SSL for debug run is fine. SSL is a deployment concern. Closing

**Comment by olynch** [comment]
I'm running with an nginx proxy that has an SSL certificate; there's no SSL in my elixir imo

**Comment by derek-zhou** [comment]
If you have proper SSL termination on the nginx everything should be fine. Is the above warning only shows when you send a email? Supposedly, local SMTP (localhost:25) should not need starttls. Maybe your particular erlang setup and smtp server did a starttls for whatever reason. I thing it can be safely ignored.
